// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leupfdemwpkfjaniekma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldXBmZGVtd3BrZmphbmlla21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjQwNzQsImV4cCI6MjA2NDg0MDA3NH0._wgXy5n1jqyrSPXVf4wATDNxKUInGpM6ylST0fVOw5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);